# Soft fog puffs from Kenney "Smoke Particles" (CC0) white puffs: blurred, shrunk, alpha only.
import sys, base64
import numpy as np
from PIL import Image, ImageFilter
src, out_ts, preview = sys.argv[1], sys.argv[2], sys.argv[3]
picks = [2, 7, 12, 18]
lines = ["// Generated by mkfog.py from Kenney Smoke Particles (CC0, whitePuff). Alpha maps, 0..255.",
         "export const FOG_PUFFS: { w: number; h: number; d: string }[] = ["]
sheet = Image.new("RGBA", (96 * len(picks), 96), (60, 90, 60, 255))
for k, i in enumerate(picks):
    im = Image.open(f"{src}/whitePuff{i:02d}.png").convert("RGBA")
    a = im.getchannel("A")
    pad = Image.new("L", (a.width + 160, a.height + 160)); pad.paste(a, (80, 80))
    pad = pad.filter(ImageFilter.GaussianBlur(26)).resize((96, 96), Image.LANCZOS)
    arr = np.asarray(pad, dtype=np.float32); arr = arr / arr.max() * 255
    arr = arr.astype(np.uint8)
    lines.append(f'  {{ w: 96, h: 96, d: "{base64.b64encode(arr.tobytes()).decode()}" }},')
    white = Image.new("RGBA", (96, 96), (255, 255, 255, 0)); white.putalpha(Image.fromarray(arr))
    sheet.alpha_composite(white, (96 * k, 0))
lines.append("];")
open(out_ts, "w").write("\n".join(lines) + "\n")
sheet.save(preview)
