# Turns CC0 colour maps into small tileable luminance maps (base64) for client/src/mapTex.data.ts.
import sys, json, base64
import numpy as np
from PIL import Image, ImageFilter
cfg = json.load(open(sys.argv[1]))  # {name: {src, size:[w,h], contrast, levels, blur}}
out = ["// Generated by mktex.py from CC0 textures (see client/art/textures/SOURCES.md). Luminance maps, 128 = the theme colour.",
       "export const MAP_TEX: Record<string, { w: number; h: number; d: string }> = {"]
for name, c in cfg.items():
    im = Image.open(c["src"]).convert("L")
    if c.get("crop"): im = im.crop(tuple(c["crop"]))
    W, H = im.size
    big = Image.new("L", (W * 3, H * 3))
    for i in range(3):
        for j in range(3): big.paste(im, (i * W, j * H))
    w, h = c["size"]
    small = big.resize((w * 3, h * 3), Image.LANCZOS).crop((w, h, 2 * w, 2 * h))
    a = np.asarray(small, dtype=np.float32)
    a = (a - a.mean()) / (a.std() + 1e-6)
    a = 128 + a * c.get("contrast", 22)
    lv = c.get("levels", 0)
    if lv: step = 256 / lv; a = np.round(a / step) * step
    a = np.clip(a, 0, 255).astype(np.uint8)
    Image.fromarray(a).save(sys.argv[2] + f"/{name}.png")
    out.append(f'  {name}: {{ w: {w}, h: {h}, d: "{base64.b64encode(a.tobytes()).decode()}" }},')
out.append("};")
open(sys.argv[3], "w").write("\n".join(out) + "\n")
